/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.Empresa;
import javax.swing.JOptionPane;

/**
 *
 * @author CAMILA
 */

public class ContratarChofer extends javax.swing.JDialog {
private Empresa empresa = Empresa.getInstance();

    /**
     * Creates new form PerfilChofer
     */
    public ContratarChofer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabDatosChofer = new javax.swing.JLabel();
        LabNombreChofer = new javax.swing.JLabel();
        TextNombreChofer = new javax.swing.JTextField();
        LabLicencia = new javax.swing.JLabel();
        BoxLicencia = new javax.swing.JComboBox();
        btnAceptar = new javax.swing.JButton();
        labCostoContratacion = new javax.swing.JLabel();
        textCostoContratacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabDatosChofer.setText("Datos del chofer ");

        LabNombreChofer.setText("Nombre: ");

        TextNombreChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreChoferActionPerformed(evt);
            }
        });

        LabLicencia.setText("Tipo de licencia");

        BoxLicencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Moto", "Carro", "Avión", "Helicoptero", "Ferry", "Barco" }));
        BoxLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxLicenciaActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        labCostoContratacion.setText("Costo de Contratacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabNombreChofer))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TextNombreChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabLicencia))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BoxLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(LabDatosChofer))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labCostoContratacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textCostoContratacion))))
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabDatosChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(LabNombreChofer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNombreChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabLicencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labCostoContratacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCostoContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        double costoContratacion = 0;
        if( empresa.getFondos()==0 ){
            JOptionPane.showMessageDialog(null, "Fondos insuficientes para realizar la contratación");
        }else{

            try{
                costoContratacion = Double.parseDouble(textCostoContratacion.getText());
                if ( costoContratacion <= empresa.getFondos()){
                //si se puede contratar             
                empresa.contratarChofer(TextNombreChofer.getText(), BoxLicencia.getSelectedIndex(), costoContratacion);
                 JOptionPane.showMessageDialog(null, "Se contrató el chofer exitosamente");
                this.dispose();//cerrar la ventana
            }else{
                
                JOptionPane.showMessageDialog(null, "Fondos insuficientes para realizar la contratación");
                this.dispose();
                
            }
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad valida");
        
            }
            
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void BoxLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxLicenciaActionPerformed

    private void TextNombreChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreChoferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreChoferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContratarChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContratarChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContratarChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContratarChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContratarChofer dialog = new ContratarChofer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BoxLicencia;
    private javax.swing.JLabel LabDatosChofer;
    private javax.swing.JLabel LabLicencia;
    private javax.swing.JLabel LabNombreChofer;
    private javax.swing.JTextField TextNombreChofer;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel labCostoContratacion;
    private javax.swing.JTextField textCostoContratacion;
    // End of variables declaration//GEN-END:variables
}

