/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.Anuncio;
import clases.Empresa;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author alvar_000
 */
public class VentanaCalcularTransporte extends javax.swing.JDialog {
    Anuncio anuncio;
    /**
     * Creates new form VentanaCalcularTransporte
     */
    public VentanaCalcularTransporte(java.awt.Dialog parent, boolean modal, Anuncio anuncio) {
        super(parent, modal);
        this.anuncio = anuncio;
        initComponents();
        txaAnuncio.setText(anuncio.toString());
        
        Empresa.getInstance().getVehiculos().stream().forEach((vehiculo) -> {
            cBoxVehiculo.addItem(vehiculo.getID());
        });
        
        Empresa.getInstance().getChoferes().stream().forEach((chofer) -> {
            cBoxChoferes.addItem(chofer.getNombre());
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cBoxVehiculo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cBoxChoferes = new javax.swing.JComboBox();
        btnEstimarT = new javax.swing.JButton();
        btnRealizarT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAnuncio = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Estimación de gastos de transporte");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setText("Seleccione el vehiculo con el que desea realizar el viaje");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanel1.add(cBoxVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, -1));

        jLabel3.setText("Seleccione el chofer que hará el viaje");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jPanel1.add(cBoxChoferes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, -1));

        btnEstimarT.setText("Estimar Transporte");
        btnEstimarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstimarTActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstimarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        btnRealizarT.setText("Realizar Transporte");
        btnRealizarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarTActionPerformed(evt);
            }
        });
        jPanel1.add(btnRealizarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        jLabel4.setText("Anuncio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

<<<<<<< HEAD
        lblAnuncio.setText("Aquí va el anuncio\nasd\nasdasda");
        jPanel1.add(lblAnuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
=======
        txaAnuncio.setEditable(false);
        txaAnuncio.setColumns(20);
        txaAnuncio.setRows(5);
        jScrollPane1.setViewportView(txaAnuncio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 480, 100));
>>>>>>> origin/master

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarTActionPerformed

    private boolean verificarVehiculo() throws Exception{
        if(Empresa.getInstance().getVehiculos().get(cBoxVehiculo.getSelectedIndex()).getVidaUtil() == 0){
            throw new Exception("El vehículo necesita mantenimiento para ser utilizado");
        }
        //return Empresa.getInstance().getVehiculos().get(cBoxVehiculo.getSelectedIndex()).getTipoVehiculo().equals(anuncio.getMedioTransporte());
        if(!Empresa.getInstance().getVehiculos().get(cBoxVehiculo.getSelectedIndex()).getTipoVehiculo().equals(anuncio.getMedioTransporte())){
            throw new Exception("Vehículo no adecuado para este medio de transporte");
        }
        if(Empresa.getInstance().getVehiculos().get(cBoxVehiculo.getSelectedIndex()).getCapacidadCargaDisponibles() < anuncio.getPesoPaquete()){
            throw new Exception("El peso del paquete es superior a la capacidad de carga del vehículo");
        }
        return true;
    }

    private boolean verificarChofer(){
        
        String idVehiculo = Empresa.getInstance().getVehiculos().get(cBoxVehiculo.getSelectedIndex()).getID();
        String prefix = idVehiculo.substring(0,3);
        switch(prefix){
            case "MOT":{
                return Empresa.getInstance().getChoferes().get(cBoxChoferes.getSelectedIndex()).obtenerLicencias().get(0);
            }
            case "CAR":{
                return Empresa.getInstance().getChoferes().get(cBoxChoferes.getSelectedIndex()).obtenerLicencias().get(1);
            }
            case "AVN":{
                return Empresa.getInstance().getChoferes().get(cBoxChoferes.getSelectedIndex()).obtenerLicencias().get(2);
            }
            case "HLP":{
                return Empresa.getInstance().getChoferes().get(cBoxChoferes.getSelectedIndex()).obtenerLicencias().get(3);
            }
            case "FRY":{
                return Empresa.getInstance().getChoferes().get(cBoxChoferes.getSelectedIndex()).obtenerLicencias().get(4);
            }
            case "BRC":{
                return Empresa.getInstance().getChoferes().get(cBoxChoferes.getSelectedIndex()).obtenerLicencias().get(5);
            }
        }
        System.out.println("La verificación de chofer no debería llegar hasta esta línea de código");
        return false;
    }
    
    
    private void btnEstimarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstimarTActionPerformed
        try {
            if(verificarVehiculo()){
                if(verificarChofer()){
                    try {
                        double costo = Empresa.getInstance().estimarCostosDeTransporte(Empresa.getInstance().getChoferes().get(cBoxChoferes.getSelectedIndex()), Empresa.getInstance().getVehiculos().get(cBoxVehiculo.getSelectedIndex()), anuncio).get(0);
                        double ganancia = Empresa.getInstance().estimarCostosDeTransporte(Empresa.getInstance().getChoferes().get(cBoxChoferes.getSelectedIndex()), Empresa.getInstance().getVehiculos().get(cBoxVehiculo.getSelectedIndex()), anuncio).get(1);
                        
                        String texto = "Fondo actual: " + Empresa.getInstance().getFondos() +"\n\nCostos de transporte: " +  costo + "\nGanancias de transporte: " +  ganancia +  "\n\nFondo posterior al transporte: " + (Empresa.getInstance().getFondos() + (ganancia-costo));
                        
                        JOptionPane.showMessageDialog(null, texto, "Estimar costos",1);
                    } catch (Exception ex) {
                        Logger.getLogger(VentanaCalcularTransporte.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"El chofer no está capacitado para manejar el vehículo seleccionado.","Error al seleccionar chofer",0);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Error al seleccionar vehículo",0);
        }
        
        
    }//GEN-LAST:event_btnEstimarTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalcularTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalcularTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalcularTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalcularTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaCalcularTransporte dialog = new VentanaCalcularTransporte(new javax.swing.JDialog(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstimarT;
    private javax.swing.JButton btnRealizarT;
    private javax.swing.JComboBox cBoxChoferes;
    private javax.swing.JComboBox cBoxVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaAnuncio;
    // End of variables declaration//GEN-END:variables
}
