/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.Anuncio;
import clases.Empresa;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Anthony
 */
public class VentanaPrincipal extends javax.swing.JFrame implements Runnable{
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        //t.start();
        
        initComponents();
        
    }
    
    @Override
    public void run(){
        
        int counter = 0;
        while(true){
            System.out.println(counter);
            lblContador.setText(Calendar.getInstance().getTime().toString());//Integer.toString(counter));
            counter++;
            
            for(int i = 0; i < Empresa.getInstance().getAnuncios().size(); i++){
                
                Empresa.getInstance().getAnuncios().get(i).reducirDuracion();
                
                
                if(Empresa.getInstance().getAnuncios().get(i).getDuracionAnuncio() == 0){
                    Empresa.getInstance().getAnuncios().remove(i);
                }
            }
            
            if(counter%5 == 0){
                Empresa.getInstance().generarAnuncio();
                
            }
            
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVehiculos = new javax.swing.JButton();
        btnChoferes = new javax.swing.JButton();
        Anuncios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEstadoFinanciero = new javax.swing.JButton();
        lblContador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVehiculos.setText("Vehículos");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });

        btnChoferes.setText("Choferes");

        Anuncios.setText("Anuncios");
        Anuncios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnunciosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Simulador de Transportes");

        btnEstadoFinanciero.setText("Estado financiero");
        btnEstadoFinanciero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoFinancieroActionPerformed(evt);
            }
        });

        lblContador.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnVehiculos)
                    .addComponent(btnChoferes)
                    .addComponent(Anuncios)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstadoFinanciero)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblContador)
                        .addGap(20, 20, 20)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVehiculos)
                .addGap(40, 40, 40)
                .addComponent(btnChoferes)
                .addGap(29, 29, 29)
                .addComponent(Anuncios)
                .addGap(30, 30, 30)
                .addComponent(btnEstadoFinanciero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        // TODO add your handling code here:
        new VentanaVehiculos(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void AnunciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnunciosActionPerformed
        // TODO add your handling code here:
        //new VentanaAnuncios(this,true).setVisible(true);
        VentanaAnuncios ventana = new VentanaAnuncios(this,true);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_AnunciosActionPerformed

    private void btnEstadoFinancieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoFinancieroActionPerformed
        // TODO add your handling code here:
        Empresa empresa = Empresa.getInstance();
        JOptionPane.showMessageDialog(rootPane, "Este es el estado financiero actual de la empresa\n"+
                "Fondos: "+empresa.getFondos()+"\n"+
                "Ganancias: "+empresa.getGanancias()+"\n"+
                "Gastos: "+empresa.getGastos(), "Estado financiero", 0);
        
    
    }//GEN-LAST:event_btnEstadoFinancieroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anuncios;
    private javax.swing.JButton btnChoferes;
    private javax.swing.JButton btnEstadoFinanciero;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContador;
    // End of variables declaration//GEN-END:variables
}

