/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.Anuncio;
import clases.Empresa;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Anthony
 */
public class VentanaPrincipal extends javax.swing.JFrame implements Runnable{
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        //t.start();
        
        initComponents();
        
        boolean combustibleIndefinido = true;
        while(combustibleIndefinido){
            System.out.println("entro al hilo");
            String precioCombustible = (String) JOptionPane.showInputDialog(null,"Ingrese el precio del litro de combustible", "Precio del combustible", 3);

            try{
                Empresa.getInstance().setPrecioXLitroCombustible(Double.parseDouble(precioCombustible));
                lblPrecioLitroCombustible.setText("Precio del litro de combustible: ₡" + precioCombustible);
                combustibleIndefinido = false;
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Debe ingresar un monto válido","Precio del litro de combustible no establecido",0);
            }

        }
        
        
        
        boolean montoIndefinido = true;
        
        while(montoIndefinido){
            String fondoInicial = (String) JOptionPane.showInputDialog(null,"Ingrese el fondo incial de la empresa", "Establecer fondo inicial", 3, new javax.swing.ImageIcon(getClass().getResource("/iconos/coins.png")),null,null);
        
            try{
                Empresa.getInstance().setFondos(Double.parseDouble(fondoInicial));
                montoIndefinido = false;
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Debe ingresar un monto válido","Fondo inicial no establecido",0);
            }
        }
       ArrayList <String> licencias = new ArrayList();
       licencias.add("Moto");
       licencias.add("Carro");
       licencias.add("Avion");
       licencias.add("Helicoptero");
       licencias.add("Ferry");
       licencias.add("Barco");
       
       ArrayList<Double> costoCapacitacion = new ArrayList(); 
       for(int i =0; i < 6;i++){ 
           boolean montoCapacitacion = true;
           
        while(montoCapacitacion){           
        
            try{
                double costo = Double.parseDouble((String) JOptionPane.showInputDialog(null,"Costo de capacitación para: " + licencias.get(i), "Establecer costo de capacitación", 3, new javax.swing.ImageIcon(getClass().getResource("/iconos/coins.png")),null,null));
                montoCapacitacion = false;
                costoCapacitacion.add(costo);
            }
            catch(Exception e){
                System.out.println("Entra al catch");
                JOptionPane.showMessageDialog(null,"Debe ingresar un monto válido","Error, verifique el monto ingresado",0);
            }
        }
         
    }
       Empresa.getInstance().setCostoCapacitacion(costoCapacitacion);
  }
    
    
    

    
    @Override
    public void run(){
        
        int counter = 0;
        while(true){
            System.out.println(counter);
            lblContador.setText(Calendar.getInstance().getTime().toString());//Integer.toString(counter));
            counter++;
            
            for(int i = 0; i < Empresa.getInstance().getAnuncios().size(); i++){
                
                Empresa.getInstance().getAnuncios().get(i).reducirDuracion();
                
                if(Empresa.getInstance().getAnuncios().get(i).getDuracionAnuncio() == 0){
                    Empresa.getInstance().getAnuncios().remove(i);
                }
            }
            
            if(counter%5 == 0){
                Empresa.getInstance().generarAnuncio(); 
            }
            
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVehiculos = new javax.swing.JButton();
        btnChoferes = new javax.swing.JButton();
        Anuncios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        lblPrecioLitroCombustible = new javax.swing.JLabel();
        btnEstadoFinanciero = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVehiculos.setText("Vehículos");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        btnChoferes.setText("Choferes");
        btnChoferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoferesActionPerformed(evt);
            }
        });
        getContentPane().add(btnChoferes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        Anuncios.setText("Anuncios");
        Anuncios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnunciosActionPerformed(evt);
            }
        });
        getContentPane().add(Anuncios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Simulador de Transportes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 336, 37));

        lblContador.setText("jLabel2");
        getContentPane().add(lblContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        lblPrecioLitroCombustible.setText("Precio del litro de combustible: ");
        getContentPane().add(lblPrecioLitroCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        btnEstadoFinanciero.setText("Estado Financiero");
        btnEstadoFinanciero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoFinancieroActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstadoFinanciero, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 320, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/FondoDePantalla.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        // TODO add your handling code here:
        new VentanaVehiculos(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btnVehiculosActionPerformed


    private void AnunciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnunciosActionPerformed
        // TODO add your handling code here:
       new VentanaAnuncios(this,true).setVisible(true);
    }//GEN-LAST:event_AnunciosActionPerformed

    private void btnChoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoferesActionPerformed
        // TODO add your handling code here:
        (new VentanaChoferes(this,true)).setVisible(true);

    }//GEN-LAST:event_btnChoferesActionPerformed

    private void btnEstadoFinancieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoFinancieroActionPerformed
       Empresa empresa = Empresa.getInstance();
        JOptionPane.showMessageDialog(rootPane, "Este es el estado financiero actual de la empresa\n"+
                "Fondos: "+empresa.getFondos()+"\n"+
                "Ganancias: "+empresa.getGanancias()+"\n"+
                "Gastos: "+empresa.getGastos(), "Estado financiero", 0);
    }//GEN-LAST:event_btnEstadoFinancieroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anuncios;
    private javax.swing.JButton btnChoferes;
    private javax.swing.JButton btnEstadoFinanciero;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblPrecioLitroCombustible;
    // End of variables declaration//GEN-END:variables
}

